---

name: "Setup HashiCorp Nomad Pack"
author: "Kerim Satirli"
description: "A GitHub Action to install a specific version of HashiCorp Nomad Pack and add it to PATH."
inputs:
  version:
    description: "The Nomad Pack version to install and add to PATH."
    required: true
    default: "latest"
outputs:
  version:
    description: "The Nomad Pack version that was installed and added to PATH."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "archive"
  color: "green"
