name: "Setup HashiCorp nomad-pack"
author: "Kerim Satirli"
description: "A GitHub Action to install a specific version of HashiCorp Packer and add it to PATH."
inputs:
  version:
    description: "The nomad-pack version to install and add to PATH. Supports semver versioning."
    required: true
    default: "latest"
outputs:
  version:
    description: "The nomad-pack version that was installed and added to PATH."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "archive"
  color: "green"
