---
name: "Security Scan: Snyk Code"

on:
  push:

jobs:
  snyk:
    runs-on: ubuntu-latest

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 1

      # see https://github.com/snyk/actions/tree/master/node
      - name: Lint Code with Snyk
        uses: snyk/actions/node@master # TSCCR: no entry for repository "snyk/actions"
        env:
          # see https://github.com/snyk/actions#getting-your-snyk-token
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          # see https://github.com/snyk/actions/tree/master/node#uploading-snyk-scan-results-to-github-code-scanning
          args: --policy-path=.snyk --sarif-file-output=snyk.sarif --org=${{ secrets.SNYK_ORG }}

#      # see https://github.com/github/codeql-action/tree/main/upload-sarif
#      - name: Upload Snyk IaC results to GitHub Code Scanning
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: snyk.sarif
