---
name: "Code Quality: Super-Linter"

on:
  push:

jobs:
  superlinter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code with Super-Linter
        uses: github/super-linter@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          JAVASCRIPT_DEFAULT_STYLE: "prettier"
          VALIDATE_JSON: true
          VALIDATE_MD: true
