---
name: "Code Quality: TypeScript"

on:
  push:

jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      matrix:
        node-version:
          - 16.x

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install NPM Packages
        run: npm install

      - name: Format TypeScript code
        run: npm run-script fmt

      - name: Build TypeScript code
        run: npm run-script build
