---
name: "Code Quality: TypeScript"

on:
  push:

jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      matrix:
        node-version:
          - 16.x

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install NPM Packages
        run: npm install

      - name: Format TypeScript code
        run: npm run-script fmt

      - name: Build TypeScript code
        run: npm run-script build
